package com.vegito.app.utils

object Localization {
    private val translations = mapOf(
        "en" to mapOf(
            "app_name" to "Vegito",
            "tagline" to "Fresh groceries. Fast delivery.",
            "start_shopping" to "Start Shopping",
            "login" to "Login",
            "sell_on_vegito" to "Sell on Vegito",
            "deliver_with_vegito" to "Deliver with Vegito",
            "home" to "Home",
            "search" to "Search",
            "cart" to "Cart",
            "orders" to "Orders",
            "profile" to "Profile",
            "fresh_near_you" to "Fresh Near You",
            "categories" to "Categories",
            "active_offers" to "Today's Offers & Discounts",
            "smart_basket" to "Smart Basket / Buy Again",
            "zigzag_section" to "Featured Fresh Pickings",
            "b2b_banner" to "Restaurant & Bulk Orders",
            "b2b_subtitle" to "Special B2B pricing for >50kg orders",
            "add_to_cart" to "Add",
            "checkout" to "Proceed to Checkout",
            "total" to "Total",
            "delivery_address" to "Delivery Address",
            "order_status" to "Order Status",
            "seller_dashboard" to "Seller Dashboard",
            "delivery_workspace" to "Delivery Workspace",
            "admin_workspace" to "Admin Control Center",
            "language" to "Language",
            "theme" to "Theme"
        ),
        "mr" to mapOf(
            "app_name" to "वेजिटो",
            "tagline" to "ताजी भाजी. जलद डिलिव्हरी.",
            "start_shopping" to "खरेदी सुरू करा",
            "login" to "लॉगिन करा",
            "sell_on_vegito" to "वेजिटोवर विक्री करा",
            "deliver_with_vegito" to "डिलिव्हरी पार्टनर बना",
            "home" to "मुख्य",
            "search" to "शोधा",
            "cart" to "कार्ट",
            "orders" to "ऑर्डर्स",
            "profile" to "प्रोफाइल",
            "fresh_near_you" to "तुमच्या जवळील ताजी भाजी",
            "categories" to "वर्गवारी",
            "active_offers" to "आजच्या खास ऑफर्स",
            "smart_basket" to "पुन्हा खरेदी करा",
            "zigzag_section" to "खास निवडक ताजे पदार्थ",
            "b2b_banner" to "हॉटेल व घाऊक खरेदी",
            "b2b_subtitle" to "५० किलोपेक्षा जास्त खरेदीवर विशेष सवलत",
            "add_to_cart" to "जोडा",
            "checkout" to "चेकआउट करा",
            "total" to "एकूण",
            "delivery_address" to "डिलिव्हरी पत्ता",
            "order_status" to "ऑर्डर स्थिती",
            "seller_dashboard" to "विक्रेता डॅशबोर्ड",
            "delivery_workspace" to "डिलिव्हरी डॅशबोर्ड",
            "admin_workspace" to "अ‍ॅडमिन सेंटर",
            "language" to "भाषा",
            "theme" to "थीम"
        ),
        "hi" to mapOf(
            "app_name" to "वेजिटो",
            "tagline" to "ताज़ी सब्जियां। तेज़ डिलीवरी।",
            "start_shopping" to "खरीदारी शुरू करें",
            "login" to "लॉगिन करें",
            "sell_on_vegito" to "वेजिटो पर बेचें",
            "deliver_with_vegito" to "डिलीवरी पार्टनर बनें",
            "home" to "होम",
            "search" to "खोजें",
            "cart" to "कार्ट",
            "orders" to "ऑर्डर्स",
            "profile" to "प्रोफाइल",
            "fresh_near_you" to "आपके पास ताज़ा माल",
            "categories" to "कैटेगरी",
            "active_offers" to "आज के खास ऑफर्स",
            "smart_basket" to "स्मार्ट बास्केट",
            "zigzag_section" to "खास ताज़ा प्रोडक्ट्स",
            "b2b_banner" to "होटल व थोक ऑर्डर",
            "b2b_subtitle" to "50 किग्रा से अधिक ऑर्डर पर भारी छूट",
            "add_to_cart" to "जोड़ें",
            "checkout" to "चेकआउट करें",
            "total" to "कुल",
            "delivery_address" to "डिलीवरी पता",
            "order_status" to "ऑर्डर स्थिति",
            "seller_dashboard" to "विक्रेता डैशबोर्ड",
            "delivery_workspace" to "डिलीवरी सेंटर",
            "admin_workspace" to "एडमिन पैनल",
            "language" to "भाषा",
            "theme" to "थीम"
        )
    )

    fun getString(key: String, lang: String = "en"): String {
        return translations[lang]?.get(key) ?: translations["en"]?.get(key) ?: key
    }
}
