// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/addresses" | "/admin" | "/admin/delivery" | "/admin/orders" | "/admin/reviews" | "/admin/sellers" | "/admin/sellers/[sellerId]" | "/auth" | "/auth/customer" | "/auth/delivery" | "/auth/login" | "/auth/register" | "/auth/seller" | "/cart" | "/categories" | "/categories/[id]" | "/customer" | "/customer/addresses" | "/customer/b2b" | "/customer/cart" | "/customer/checkout" | "/customer/favorites" | "/customer/notifications" | "/customer/orders" | "/customer/orders/[id]" | "/customer/orders/[id]/track" | "/customer/profile" | "/customer/settings" | "/customer/track" | "/customer/track/[taskId]" | "/dashboard" | "/delivery" | "/delivery/history" | "/delivery/live-map" | "/delivery/map" | "/delivery/orders" | "/delivery/profile" | "/delivery/reviews" | "/delivery/settings" | "/delivery/tasks" | "/explore" | "/favorites" | "/how-it-works" | "/notifications" | "/orders" | "/orders/[id]" | "/products" | "/products/[id]" | "/profile" | "/search" | "/seller" | "/seller/analytics" | "/seller/bulk-orders" | "/seller/complaints" | "/seller/deliveries" | "/seller/deliveries/active" | "/seller/earnings" | "/seller/inventory" | "/seller/orders" | "/seller/products" | "/seller/products/new" | "/seller/profile" | "/seller/reviews" | "/seller/settings" | "/settings" | "/unauthorized"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/admin/sellers/[sellerId]" | "/categories/[id]" | "/customer" | "/customer/orders/[id]" | "/customer/track/[taskId]" | "/delivery" | "/orders/[id]" | "/products/[id]" | "/seller"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/addresses": {}
  "/admin": {}
  "/admin/delivery": {}
  "/admin/orders": {}
  "/admin/reviews": {}
  "/admin/sellers": {}
  "/admin/sellers/[sellerId]": { "sellerId": string; }
  "/auth": {}
  "/auth/customer": {}
  "/auth/delivery": {}
  "/auth/login": {}
  "/auth/register": {}
  "/auth/seller": {}
  "/cart": {}
  "/categories": {}
  "/categories/[id]": { "id": string; }
  "/customer": {}
  "/customer/addresses": {}
  "/customer/b2b": {}
  "/customer/cart": {}
  "/customer/checkout": {}
  "/customer/favorites": {}
  "/customer/notifications": {}
  "/customer/orders": {}
  "/customer/orders/[id]": { "id": string; }
  "/customer/orders/[id]/track": { "id": string; }
  "/customer/profile": {}
  "/customer/settings": {}
  "/customer/track": {}
  "/customer/track/[taskId]": { "taskId": string; }
  "/dashboard": {}
  "/delivery": {}
  "/delivery/history": {}
  "/delivery/live-map": {}
  "/delivery/map": {}
  "/delivery/orders": {}
  "/delivery/profile": {}
  "/delivery/reviews": {}
  "/delivery/settings": {}
  "/delivery/tasks": {}
  "/explore": {}
  "/favorites": {}
  "/how-it-works": {}
  "/notifications": {}
  "/orders": {}
  "/orders/[id]": { "id": string; }
  "/products": {}
  "/products/[id]": { "id": string; }
  "/profile": {}
  "/search": {}
  "/seller": {}
  "/seller/analytics": {}
  "/seller/bulk-orders": {}
  "/seller/complaints": {}
  "/seller/deliveries": {}
  "/seller/deliveries/active": {}
  "/seller/earnings": {}
  "/seller/inventory": {}
  "/seller/orders": {}
  "/seller/products": {}
  "/seller/products/new": {}
  "/seller/profile": {}
  "/seller/reviews": {}
  "/seller/settings": {}
  "/settings": {}
  "/unauthorized": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/admin/sellers/[sellerId]": never
  "/categories/[id]": never
  "/customer": never
  "/customer/orders/[id]": never
  "/customer/track/[taskId]": never
  "/delivery": never
  "/orders/[id]": never
  "/products/[id]": never
  "/seller": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
