// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/addresses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/addresses">> = Specific
  const handler = {} as typeof import("../../app/addresses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/delivery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/delivery">> = Specific
  const handler = {} as typeof import("../../app/admin/delivery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/orders">> = Specific
  const handler = {} as typeof import("../../app/admin/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reviews">> = Specific
  const handler = {} as typeof import("../../app/admin/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/sellers/[sellerId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sellers/[sellerId]">> = Specific
  const handler = {} as typeof import("../../app/admin/sellers/[sellerId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/sellers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sellers">> = Specific
  const handler = {} as typeof import("../../app/admin/sellers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/customer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/customer">> = Specific
  const handler = {} as typeof import("../../app/auth/customer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/delivery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/delivery">> = Specific
  const handler = {} as typeof import("../../app/auth/delivery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../app/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth">> = Specific
  const handler = {} as typeof import("../../app/auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/register">> = Specific
  const handler = {} as typeof import("../../app/auth/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/auth/seller/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/seller">> = Specific
  const handler = {} as typeof import("../../app/auth/seller/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cart">> = Specific
  const handler = {} as typeof import("../../app/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/categories/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categories/[id]">> = Specific
  const handler = {} as typeof import("../../app/categories/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categories">> = Specific
  const handler = {} as typeof import("../../app/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/customer/addresses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/addresses">> = Specific
  const handler = {} as typeof import("../../app/customer/addresses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/customer/b2b/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/b2b">> = Specific
  const handler = {} as typeof import("../../app/customer/b2b/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/customer/cart/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/cart">> = Specific
  const handler = {} as typeof import("../../app/customer/cart/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/customer/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/checkout">> = Specific
  const handler = {} as typeof import("../../app/customer/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/customer/favorites/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/favorites">> = Specific
  const handler = {} as typeof import("../../app/customer/favorites/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/customer/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/notifications">> = Specific
  const handler = {} as typeof import("../../app/customer/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/customer/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/orders/[id]">> = Specific
  const handler = {} as typeof import("../../app/customer/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/customer/orders/[id]/track/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/orders/[id]/track">> = Specific
  const handler = {} as typeof import("../../app/customer/orders/[id]/track/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/customer/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/orders">> = Specific
  const handler = {} as typeof import("../../app/customer/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/customer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer">> = Specific
  const handler = {} as typeof import("../../app/customer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/customer/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/profile">> = Specific
  const handler = {} as typeof import("../../app/customer/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/customer/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/settings">> = Specific
  const handler = {} as typeof import("../../app/customer/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/customer/track/[taskId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/track/[taskId]">> = Specific
  const handler = {} as typeof import("../../app/customer/track/[taskId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/customer/track/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customer/track">> = Specific
  const handler = {} as typeof import("../../app/customer/track/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/delivery/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/delivery/history">> = Specific
  const handler = {} as typeof import("../../app/delivery/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/delivery/live-map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/delivery/live-map">> = Specific
  const handler = {} as typeof import("../../app/delivery/live-map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/delivery/map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/delivery/map">> = Specific
  const handler = {} as typeof import("../../app/delivery/map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/delivery/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/delivery/orders">> = Specific
  const handler = {} as typeof import("../../app/delivery/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/delivery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/delivery">> = Specific
  const handler = {} as typeof import("../../app/delivery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/delivery/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/delivery/profile">> = Specific
  const handler = {} as typeof import("../../app/delivery/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/delivery/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/delivery/reviews">> = Specific
  const handler = {} as typeof import("../../app/delivery/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/delivery/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/delivery/settings">> = Specific
  const handler = {} as typeof import("../../app/delivery/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/delivery/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/delivery/tasks">> = Specific
  const handler = {} as typeof import("../../app/delivery/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/explore/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/explore">> = Specific
  const handler = {} as typeof import("../../app/explore/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/favorites/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/favorites">> = Specific
  const handler = {} as typeof import("../../app/favorites/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/how-it-works/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/how-it-works">> = Specific
  const handler = {} as typeof import("../../app/how-it-works/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../app/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders/[id]">> = Specific
  const handler = {} as typeof import("../../app/orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/orders">> = Specific
  const handler = {} as typeof import("../../app/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/products/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/[id]">> = Specific
  const handler = {} as typeof import("../../app/products/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products">> = Specific
  const handler = {} as typeof import("../../app/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/search">> = Specific
  const handler = {} as typeof import("../../app/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/seller/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller/analytics">> = Specific
  const handler = {} as typeof import("../../app/seller/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/seller/bulk-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller/bulk-orders">> = Specific
  const handler = {} as typeof import("../../app/seller/bulk-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/seller/complaints/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller/complaints">> = Specific
  const handler = {} as typeof import("../../app/seller/complaints/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/seller/deliveries/active/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller/deliveries/active">> = Specific
  const handler = {} as typeof import("../../app/seller/deliveries/active/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/seller/deliveries/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller/deliveries">> = Specific
  const handler = {} as typeof import("../../app/seller/deliveries/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/seller/earnings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller/earnings">> = Specific
  const handler = {} as typeof import("../../app/seller/earnings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/seller/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller/inventory">> = Specific
  const handler = {} as typeof import("../../app/seller/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/seller/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller/orders">> = Specific
  const handler = {} as typeof import("../../app/seller/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/seller/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller">> = Specific
  const handler = {} as typeof import("../../app/seller/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/seller/products/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller/products/new">> = Specific
  const handler = {} as typeof import("../../app/seller/products/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/seller/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller/products">> = Specific
  const handler = {} as typeof import("../../app/seller/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/seller/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller/profile">> = Specific
  const handler = {} as typeof import("../../app/seller/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/seller/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller/reviews">> = Specific
  const handler = {} as typeof import("../../app/seller/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/seller/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seller/settings">> = Specific
  const handler = {} as typeof import("../../app/seller/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/unauthorized/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unauthorized">> = Specific
  const handler = {} as typeof import("../../app/unauthorized/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/sellers/[sellerId]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin/sellers/[sellerId]">> = Specific
  const handler = {} as typeof import("../../app/admin/sellers/[sellerId]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/categories/[id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/categories/[id]">> = Specific
  const handler = {} as typeof import("../../app/categories/[id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/customer/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/customer">> = Specific
  const handler = {} as typeof import("../../app/customer/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/customer/orders/[id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/customer/orders/[id]">> = Specific
  const handler = {} as typeof import("../../app/customer/orders/[id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/customer/track/[taskId]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/customer/track/[taskId]">> = Specific
  const handler = {} as typeof import("../../app/customer/track/[taskId]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/delivery/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/delivery">> = Specific
  const handler = {} as typeof import("../../app/delivery/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/orders/[id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/orders/[id]">> = Specific
  const handler = {} as typeof import("../../app/orders/[id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/products/[id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/products/[id]">> = Specific
  const handler = {} as typeof import("../../app/products/[id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/seller/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/seller">> = Specific
  const handler = {} as typeof import("../../app/seller/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
