"use client";
import Link from "next/link";
import { use } from "react";
import { Suspense } from "react";
import { useSearchParams } from "next/navigation";
import { useQuery } from "@tanstack/react-query";
import { ChevronLeft, ShoppingBasket } from "lucide-react";
import { getProduct } from "@/lib/api/products";
function ProductContent({params}:{params:Promise<{id:string}>}){const { id: shellId }=use(params);const id=useSearchParams().get("id")??shellId;const query=useQuery({queryKey:["product",id],queryFn:()=>getProduct(id),enabled:id!=="_"});if(query.isLoading)return <main className="simple-page"><p className="helper">Loading vegetable details…</p></main>;if(query.isError||!query.data)return <main className="simple-page"><p className="inline-message">We couldn’t find that product.</p></main>;const p=query.data;const price=p.min_price==null?null:Number(p.min_price);return <main className="simple-page detail-page"><Link href="/categories" className="back-link"><ChevronLeft size={17}/> Back to market</Link><div className="detail-grid"><div className="detail-art">{({tomato:"🍅",potato:"🥔",onion:"🧅",spinach:"🥬",banana:"🍌"}[p.name.toLowerCase()]??"🥕")}</div><div><p className="section-kicker">{p.is_in_stock?"AVAILABLE TODAY":"SELLERS ARE RESTOCKING"}</p><h1>{p.name}</h1><p className="detail-copy">{p.description ?? "Product details will be shared by the local seller."}</p><p className="detail-price">{price==null?"Price will appear when stock is listed":<>₹{price}<small> / {p.unit}</small></>}</p><p className="helper">{p.seller_products[0]?.seller_business_name ?? "No seller has listed this product yet"}</p><button className="primary-action" disabled={!p.is_in_stock||price==null}><ShoppingBasket size={18}/>{p.is_in_stock&&price!=null?"Log in to add to basket":"Currently unavailable"}</button></div></div></main>}
export default function ProductPage({params}:{params:Promise<{id:string}>}){return <Suspense fallback={<main className="simple-page"><p className="helper">Loading vegetable details…</p></main>}><ProductContent params={params}/></Suspense>}
